<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CityAbejorralAbriaquiAlejandr_c4e22e</name>
   <tag></tag>
   <elementGuidId>e6786917-5b66-4857-a8fe-9d3e7fedc45d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cityId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>last cities</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
   Select City
AbejorralAbriaquiAlejandriaAmagaAmalfiAndesAngelopolisAngosturaAnoriAntioquiaAnzaApartadoArboletesArgeliaArmeniaBarbosaBelloBelmiraBetaniaBetuliaBolivarBricenoBuriticaCaceresCaicedoCaldasCampamentoCanasgordasCaracoliCaramantaCarepaCarmen de ViboralCarolinaCaucasiaChigorodoCisnerosCocornaConcepcionConcordiaCopacabanaDabeibaDon MatiasEbejicoEl BagreEntrerriosEnvigadoFredoniaFrontinoGiraldoGirardotaGomez PlataGranadaGuadalupeGuarneGuatapeHeliconiaHispaniaItaguiItuangoJardinJericoLa CejaLa EstrellaLa PintadaLa UnionLiborinaMaceoMarinillaMedellinMontebelloMurindoMutataNarinoNechiNecocliOlayaPenolPequePueblorricoPuerto BerrioPuerto NarePuerto TriunfoRemediosRetiroRionegroSabanalargaSabanetaSalgarSan AndresSan CarlosSan FranciscoSan JeronimoSan Jose de la MontanaSan Juan de UrabaSan LuisSan PedroSan Pedro de UrabaSan RafaelSan RoqueSan VicenteSanta BarbaraSanta Rosa de OsosSanto DomingoSantuarioSegoviaSonsonSopetranTamesisTarazaTarsoTitiribiToledoTurboUramitaUrraoValdiviaValparaisoVegachiVeneciaVigia del FuerteYaliYarumalYolomboYondoZaragoza</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityId&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cityId']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/select[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::select[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[4]</value>
   </webElementXpaths>
</WebElementEntity>
